---
title: Saved by the pulse?  Separating the effects of total and temporal food abundance
  on the development and performance of bumble bee microcolonies
author:
- Jeremy Hemberger
- Agathe Frappa
- Grant Witynski
- Claudio Gratton
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
  html_document:
    df_print: paged
fontfamily: mathpazo
fontsize: 11pt
geometry: margin = 1in
header-includes:
- \usepackage{setspace}\doublespacing
- \usepackage[left]{lineno}
- \linenumbers
- \usepackage{dcolumn}
- \usepackage{caption}
- \usepackage{float}
- \usepackage{afterpage}
- \usepackage{siunitx}
keywords: _Bombus impatiens_, colony growth, floral resources, temporal variability,
  agroecosystems
bibliography: ./library.bib
spacing: double
abstract: The loss of flower-rich habitat in agricultural landscapes is a key factor contributing
  to bumble bee declines across Europe and North America.  Yet, agricultural intensification
  has not only altered flower abundance in the landscape, but also affected when flowers
  are available during the season (e.g., mass-flowering crops).  While we know that
  both total pollen and nectar as well as temporal availability can impact bumble
  bee colony success (growth and reproductive output), we have yet to understand how
  these two factors combined might manifest.  We designed an experiment to decouple
  the effects of total food abundance and its temporal availability on bumble bee
  microcolony development by exposing them to either constant or pulsed food availability
  at two ration levels, 100% and 60% _ad-libitum_ food abundance.  Microcolonies provided
  constant, full-rations of food grew the most, while those fed variable, but full-rations
  gained less mass over the course of the experiment.  Regardless of the temporal presentation of food, microcolonies fed 60% _ad-libitum_ rations gained little mass over the experiment.  Reproductive output
  was greatest in microcolonies fed full-rations, regardless of the temporal availability
  of food, while those given 60% rations produced on average 27% fewer drones.  This
  study highlights the importance of flower abundance for
  both colony growth and reproduction, regardless of how food is presented (e.g., constantly or in a pulse).  Together, these results indicate that increasing total food abundance will have the greatest, positive impact on colony fitness.
---

# Introduction
Bumble bee declines across Europe and North America are driven by a number of interacting anthropogenic factors such as pesticides, [@McArt2017], novel diseases from managed bees [@Brown2016a; @Furst2014] and climate change [@Kerr2015]). There is a growing consensus that habitat loss is the most important driver of bee declines [@Roulston2011; @Senapathi2015a; @Goulson2016].  In the US Midwest, two centuries of agricultural intensification [defined here as the spatially extensive increase of agrichemical use and proliferation of monocultures e.g., @Benton2003] has altered bumble bee habitat, supplanting once continuous landscapes of prairie, savanna, and wetlands with highly productive agricultural crops [@Smith1998; @Rhemtulla2007].  Coincident with the transition to primarily agricultural land uses in the US, several species of bumble bee have declined precipitously [@Grixti2009; @Cameron2011; @Jacobson2018a].

Most importantly, agricultural intensification has led to wholesale change in the abundance and temporal availability of floral resources in the landscape [@Goulson2008; @Williams2012b; @Schellhorn2015c; @Goulson2015c; @Vaudo2018].  Historically, landscapes containing a continuous supply of diverse floral resources [e.g., tall-grass prairies @Hines2005] were prolific, however many of these landscapes have been lost to row-crop agriculture [@Smith1998], especially in the American Midwest.  These landscapes, often devoid of flowering weeds, are largely depauperate of floral food resources for bumble bees aside from small patches of remnant natural habitat.  In contrast, some agricultural landscapes contain mass-flowering crops (e.g., fruit crops, canola) that provide large pulses of floral resources, albeit over a short time period [@Westphal2009a; @Williams2012b; @Holzschuh2013; @Rundlof2014].  With respect to floral resource abundance, a range of possible food landscapes exist in agriculturally dominated regions, ranging from those with abundant, but temporally constrained floral resources, to those nearly devoid of floral resources.

Total floral resource abundance is an important factor that contributes to the growth and reproductive success of bumble bee colonies.  For example, worker production is dependent on pollen and nectar influx to the colony; shortfalls can be detrimental to worker output [@Williams2012b; @Cartar1991; @Sutcliffe1988], and reproductive (drone and gyne) output can be enhanced with increased food availability [@Pelletier2003; @Crone2016].  Despite variable effect sizes and experimental methodologies, most studies tend to agree that increased flower abundance leads to increased bumble bee abundance [e.g., @Carvell2007; @Blaauw2014] and/or colony performance [e.g., @Spiesman2017].

While total food availability is key for developing bumble bee colonies, when food is available is also potentially important [@Schellhorn2015c].  Because bumble bee colonies have three distinct bottlenecks wherein food availability is crucial to colony success (queen colony establishment, colony worker buildup, and reproductive production), food shortages during any period of the colony life cycle can impair colony function.  As such, continuous availability of flowers in the landscape is believed to be paramount for bumble bees [@Martins2018].  Past work has examined the effect of total food abundance [@Rotheray2017] and temporal availability [@Schmid-Hempel1998a] on colony development independently, however we have yet to test the interactive effect of the two.  Understanding this interaction is crucial as we tend to see both total and temporal floral resource abundance vary together in agricultural landscapes.

Thus, is a lack of food, the temporal availability of food, or both limiting bumble bee colony success?  Parsing these two interacting factors apart could help explain specific mechanisms underlying bumble bee declines in agricultural landscapes, as well as suggest conservation interventions.  The interaction between total floral resource abundance and temporal availability in the landscape can be visualized conceptually as two potentially independent factors (Fig.1).  In this abstraction, landscapes in the lower left quadrant contain few flowers that are constantly available over the course of the growing season.  This can be contrasted with landscapes in the upper left quadrant that contain the same total abundance of flowers but that occur during two narrow pulses (e.g., two mass-flowering crops).  Fiven that bumble bees are obligate flower visitors [@Junker2010] existing as long-lived colonies, we might expect that access to an abundance of flowers that are consistently available over time (e.g., landscapes in lower right quadrant) would be critical for successful colony development.

To decouple the effects of total food abundance and temporal availability on bumble bee colony development, we designed a 2x2 factorial experiment that varied total food amount (both pollen and nectar) and its temporal availability.  Treatment designs were meant to simulate hypothetical scenarios that provide bumble bees either constantly available, or pulsed food resources at two ration levels: high (100% _ad-libitum_) and low (60% _ad-libitum_) (Fig.1).  These may represent different modalities of food intake corresponding to different types of agricultural landscapes.  For example, bumble bees might experience landscapes containing few floral resources and only during one short period of time (e.g., Fig.1, upper left quadrant) or a landscape containing many floral resources that are consistently available (e.g., Fig.1, lower right quadrant).

Using microcolonies of the Common Eastern bumble bee (_Bombus impatiens_ Cresson), we tested the following hypotheses: (1) microcolonies provided high rations (pollen and nectar) in constant, equally sized portions would gain the most mass and have the greatest reproductive output; (2) microcolonies provided high rations in pulses separated by periods of relative starvation would perform slightly worse compared to those provided high, equally sized rations, as _B. impatiens'_ population stability in agricultural landscapes suggests resilience to land-use change and variability in food quantity [@Cameron2011; @Grab2019]; (3) microcolonies provided low rations would perform worst, regardless of whether food was presented in equally sized or pulsed rations, as colonies would be too nutritionally stressed regardless of relatively large, episodic influxes of food in the pulsed colonies.

# Materials and methods
## Experimental design and procedure
To assess the impact of varying total, and temporal food abundance on bumble bee colony production, we designed a 2x2 factorial experiment utilizing microcolonies of _B. impatiens_.  Microcolonies were used as proxies to full colonies given their ease of establishment and well-documented analogs to full colony development [@Tasei2008; @Dance2017; @Moerman2017].

In three experimental rounds, we established microcolonies from: (Round 1) 10 queen-right colonies sourced from Koppert Biological Systems (Howell, MI) in February of 2018; (Round 2) 10 queen-right colonies from Koppert Biological Systems in May of 2018; (Round 3) 10 queen-right colonies sourced from BioBest Biological (Romulus, MI) in October of 2018.  In each round, microcolony initiation was identical. We removed sets of 5 workers from a random colony and placed sets into 28 acrylic plastic microcolony rearing boxes (10 x 15 x 10 cm), provisioning each with 2 grams of honey bee collected pollen (provided by Koppert Biological Systems) homogenized with nectar and sealed in honey bee wax, as well as _ad-libitum_ nectar through a sub-floor cotton wick and reservoir (ProSweet: MannLake LTD, Minnesota).  To allow microcolony initiation, we left colonies undisturbed for approximately 1 week.  Once we observed evidence of microcolony establishment (egg and larval brood masses visible) in each replicate box, we removed any remaining pollen and nectar, and initiated treatment regimes.  In order to ensure microcolonies had equal capacity to respond to food availability (i.e., 5 workers per box), we replaced any deceased workers throughout the experiment with randomly selected workers from queen-right feeder colonies.

Over 8 weeks, we simulated landscape-scale food availability of both pollen and nectar in four treatments: (1) low-constant; (2) high-constant; (3) low-pulsed; and (4) high-pulsed. Each represented a hypothetical landscape whereby total food abundance, and temporal availability were independently altered according to the factorial design (Fig1).  Low-constant microcolonies were fed equal-sized rations at 60% _ad-lib_ levels; high-constant microcolonies fed equal-sized rations at 100% _ad-lib_ levels. High-pulsed microcolonies were fed 100% _ad-lib_ rations (equal pollen and nectar to high-constant treatment) but food resources were provided as two large pulses with periods of relative starvation (at 60% _ad-lib_) spanning the period between pulses. Low-pulsed microcolonies were fed 60% _ad-lib_ rations with temporal availability the same as the high-pulsed treatment, with periods of relative starvation at 38% _ad-lib_ spanning the period between pulses.  Seven microcolonies were randomly assigned to each treatment.  To determine the total amount of pollen and nectar to supply in the treatments over the course of the experiment, we used measurements reported in [@Rotheray2017] (which reported on _ad-lib_ consumption rates of the European analog of _B. impatiens_, _B. terrestris_), scaling total experiment food abundance at 100% _ad-lib_ to 5 workers (approximately 33 grams of pollen and 300 grams of nectar) over 17 feeding intervals (~ 8 weeks).  Low-ration treatments were scaled to 60% of that value.

Every 3 days (hereafter interval feeding days: IFD), we massed whole microcolonies by placing them on a scale and recording mass to the nearest 0.01 grams.  After massing, we fed microcolonies by providing an appropriately massed pollen ball and nectar cup (see Supplemental Material for feeding schedule and layout of microcolony box) depending on the food treatment.  After every 3 IFDs (every 9 Julian days), we removed and massed the pollen that was not consumed in the microcolony to calculate consumption. Nectar rations were replaced at every IFD - each massed before addition and after removal to determine nectar consumption [similar to @Rotheray2017].  Nectar rations were kept in sealed containers with only the nectar wick exposed, thereby minimizing any nectar evaporation.  We massed the microcolony before the removal or addition of food to ensure that measurements were comparable between IFDs.

To determine if treatments affected the relative fitness of each microcolony, we censused colonies at each IFD.  Censusing included tallying worker mortality and drone (male) emergence.  We then removed and froze drones for subsequent analysis in which we determined average drone wet mass per IFD for each microcolony and individual drone intertegular distance (to nearest 0.01mm using ProgRes CapturePro v2.0).

## Data analysis
We performed all data management and statistical analyses in R, version 3.5.3 [@rcite]. For each colony, we calculated the estimated "actual" microcolony mass relative to IFD 1.  The goal of this calculation was to best determine how much biomass was being added to the brood mass within the microcolony between IFDs while factoring out added, but not consumed, food:

$$
\begin{aligned}
Estimated Brood Mass_{IFD = n} = Microcolony Mass_{IFD = n} - Microcolony Mass_{IFD = 1} - \\
(Pollen Added_{IFD = n} - Pollen Consumed_{IFD = n})
\end{aligned}
$$

where $Microcolony Mass_{IFD}$ is the mass of the entire microcolony (including box) at `IFD = n`;  $Microcolony Mass_{IFD = 1}$ is the mass of the entire microcolony on the first IFD: we calculated mass gains relative the mass at IFD = 1; $Pollen Consumed_{IFD = n}$ is the average pollen consumed at `IFD = n`, determined by taking the pollen consumed over the course of 3 IFDs (determined after removing unconsumed pollen every 3 IFDs) and dividing by 3; and $Pollen Added_{IFD = n}$ is the mass of pollen added within the last 3-4 IFDs that had not yet been consumed.  In the event that missing data prevented $Estimated Brood Mass_{IFD = n}$ from being determined (< 1% of data), we interpolated the missing values using the `na.approx` function from the R package `zoo` [@zoo].  Nectar storage/consumption within the microcolony was not considered for the $Microcolony Mass_{IFD = n}$ calculation, as we were not able to parse out nectar consumed by workers from nectar moved by workers to honey pots in the brood mass.  At the end of the experiment, we also measured the mass of the brood cluster (including all wax, remaining pupae, larvae, eggs, and nectar) alone after removing them from the microcolony boxes.

To evaluate whether treatments affected end of experiment brood mass, drone production, drone fitness parameters (wet mass and IT distance), or worker mortality, we constructed linear mixed-effects models (LMMs) on the combined data set from all three experimental rounds using the `nlme` package [@nlme].  Each model took the general form of a given response variable as a function of treatment (2 x 2 factorial between total food abundance and temporal variability) and experimental round, with random intercept and slope estimates for each microcolony.  We estimated treatment means from LMMs [package: `lsmeans` @lsmeans] and used Tukey corrected pair-wise comparisons [package: `multcomp` @multcomp] to determine significance across treatments.  Additional contrasts and effect sizes were calculated using the `emmeans` package [@emmeans].

We also constructed repeated measures ANOVAs using the `nlme` package to model colony mass, IFD average and cumulative drone production, IFD average and cumulative worker mortality, as well as IFD average and cumulative nectar and pollen consumption throughout the course of the 8-week experiments.  These models took the general form of a given response as a function of treatment, date, and round, with a random slope and intercept estimates for each microcolony.  To account for temporal autocorrelation, each analysis included a first order autocorrelation structure (function: `corAR1`) with a time covariate of measurement date and a grouping factor of colony identity.  We specified the autocorrelation correction using the lag = 1 value from an identical model fitted with no autocorrelation structure.

Lastly, we calculated the growth rate of each microcolony for time periods relative to food pulses (Before pulse 1, during pulse 1, after pulse 1 and before pulse 2, during pulse 2, and after pulse2).  This was accomplished by fitting a linear model of microcolony mass as a function of IFD (time) for each replicate microcolony [similar to analysis of @Crone2016, but with linear rather than exponential fitted models].  We then extracted each slope coefficient (i.e., the growth rate for a given microcolony during an aforementioned time period) and constructed an ANOVA for each time period to determine differences in growth rates among treatments, within time periods.  The _P_-values associated with our initial slope estimates (mass as a function of IFD) were used to test whether growth was different than zero for a given time period.  We also constructed a repeated measures ANOVA for all slope estimates across all time periods to determine if there were statistical differences in temporal microcolony growth rates.

# Results
## Microcolony establishment
Overall, microcolony establishment success was high across experimental rounds, with only 3 of 84  failing to initiate (96% success).  Two additional microcolonies contained a hyper-aggressive worker that killed all original and replacement nest-mates when establishing dominance.  Despite increased aggression, these single-worker colonies still produced males.  However, we removed them from analyses as the response of a single-worker microcolony to treatments was not comparable to standard, five-worker microcolonies.

## Microcolony growth (mass and food consumption)
End of experiment microcolony mass was driven by an interaction of both total food abundance, as well as temporal availability (Fig 2B,D: interaction effect, F~1,24~ = 7.77, _P_ = 0.01).  High-constant end of experiment microcolony mass was, on average, 92% greater than low-constant microcolonies (Fig 2B, t~24~ = 5.33, _P_ < 0.001).  High-pulsed end of experiment microcolony mass was 27% more than low-pulsed microcolonies, however the difference was not statistically clear (Fig 2D, t~24~ = 1.77 , _P_ = 0.311).  Average mass at the end of the experiment for high-constant was 56% greater relative to high-pulsed microcolonies (t = 4.37, _P_ = 0.001).  There was a statistically clear effect of experimental round on end of experiment mass, with rounds 2 and 3 overall weighing less at the end of the experiment relative to round 1 (F~1,45~ = 35.88, _P_ < 0.001).  However, the pattern of end of experiment mass across treatments was consistent between rounds (F~1,45~ = 3.18, _P_ = 0.081), thus we present pooled data in figures.

Microcolony growth rates over the course of the experiment varied as a function of both total food abundance and temporal availability (Fig 3: F~1,24~ = 12.13, _P_ = 0.002).  Overall, high-constant microcolony average growth rates were the highest (t~24~ = 5.06, _P_ < 0.001), while low-constant microcolony growth rates were only statistically above 0 during one time period (before pulse 1).  Growth rate patterns were similar among both high- and low-pulsed treatments.  Both also experienced negative growth during periods following food pulses (Fig3: after pulse 1/before pulse2, after pulse 2).  Mass gain for was negligible during the first pulse, but it was greatest during the second food pulse for both high- and low-pulsed treatments.

The effect of treatments on pollen consumption varied by experimental round (F~2,41~ = 5.72, _P_ = 0.006), but the effect of treatments was similar across rounds (Treatment * Round: F~2,41~ = 2.98, _P_ = 0.068).  Within treatments, only total food abundance affected pollen consumption (F~1,24~ = 22.83, _P_ < 0.001), with high-constant microcolonies consuming the most (Pollen: 14.80 +/- 0.813 grams total).  High-pulsed ration microcolony pollen consumption was not significantly different than low-constant, or low-pulsed ration microcolonies, despite a 40% difference in pollen availability over the course of the experiment.  Nectar consumption followed a similar pattern with consumption driven by total abundance (Supplemental Fig2: F~1,24~ = 60.98, _P_ < 0.001).

## Microcolony demography (drone production and worker mortality)
We found that total drone production increased with total food abundance (Fig 4: F~1,24~ = 12.98, _P_ = 0.001).  High-constant ration microcolonies produced numerically the most males, but there was not a clear difference between high-constant and high-pulsed microcolonies (t~24~ = 1.59, _P_ = 0.398).  Both low ration treatments produced on average 27% fewer drones, regardless of the temporal availability.  There was an effect of experimental round on drone production, with rounds 2 and 3 overall producing fewer drones than in round 1.  Like with end of experiment mass, the pattern of drone production relative to treatments was similar across experimental rounds (F~1,45~ = 0.94, _P_ = 0.336).  Worker mortality was identical regardless of treatment, with on average 9 worker deaths per microcolony throughout the course of the 8 week experiment (average of 1.1 per week).

The efficiency of conversion from food to drone was roughly similar across treatments: to produce 1 drone required on average $0.70 \pm 0.08$ grams of pollen and $10 \pm 2.54$ grams of nectar.  While there were no clear statistical differences (treatment ration size effect: F~1,24~ = 0.192, _P_ = 0.664; treatment pulse effect: F~1,24~ = 0.03, _P_ = 0.853), high-constant ration and low-pulsed microcolonies were numerically more efficient in producing drones, requiring on average 18% less pollen to produce a single drone.  Low-constant and high-pulsed microcolonies were the least efficient, especially with nectar, requiring 56% more to produce a single male relative to high-constant and low-pulsed microcolonies. However, the differences were not statistically clear.

## Drone size
Drone size (as measured by average individual wet mass) was marginally greater in microcolonies provided high rations, with drones weighing on average 16% more than low ration microcolonies (F~1,24~ = 8.83, _P_ = 0.006).  However, post-hoc Tukey HSD tests did not show clear statistical differences among the treatment groups.  Intertegular distance did not vary across treatment groups, with drone body size being within tenths of a millimeter similar across treatments.

# Discussion
By manipulating the amount and temporal availability of pollen and nectar, we show that both temporal availability and total food amount affect microcolony growth and reproduction, respectively.  At the end of experiment, colony mass was greatest when microcolonies were provided constant, high rations of pollen and nectar.  This pattern matched our prediction that bumble bee microcolonies would grow the most when provided resources that mimic landscapes containing a high abundance of temporally consistent resources.  Indeed, microcolonies provided either low or temporally variable rations struggled to gain mass, with several exhibiting a net loss over the experiment.  However, drone production, arguably the most important metric of microcolony success, was only impacted by total food amount: colonies fed high rations produced more drones, regardless of temporal availability (i.e., high-constant vs. high-pulsed).  The contrasting effects of total [e.g., @Rotheray2017] and temporal [e.g., @Schmid-Hempel1998a] food availability demonstrated in this study suggest that, while both factors are important to the overall success of _B. impatiens_ microcolonies, total food abundance is more important to reproductive output.

## Microcolony mass gain
Microcolonies provided constant, high rations of food consistently gained mass over the course of the experiment. Regardless of their magnitude, food pulses were unable to rescue microcolony mass from periods of food scarcity. In fact, microcolonies experiencing pulsed food availability exhibited dramatic swings in mass gain and loss coincident with pulse and dearth periods, respectively. In contrast, microcolonies experiencing constant rations were more consistent in their mass gain, with high ration treatments on average gaining mass across all experimental periods, and low ration treatments effectively gaining zero net mass over the course of the experiment.

Many studies examining bumble bee colony responses to environmental variables use mass as a proxy for reproductive output [@Goulson2002c; @Elliott2009; @Westphal2009a; @Hass2018a]. Indeed, mass in our experiments correlated with increased reproductive output (especially in the case of high-constant microcolonies). In the absence of demographic data, the average lower final mass of high-pulsed microcolonies might have suggested lower colony reproductive output. However, drone production was equivalent in pulsed, high ration colonies - a signal that colony mass alone may not tell the complete story of bumble bee colony success. This finding corroborates other studies examining bumble bee reproductive success [@Williams2012b], and highlights the importance of additional supporting evidence to accompany trends in colony mass gain in order to fully understand colony fitness.

For our experiment, microcolony mass was our estimate of the total biomass of workers, brood, and nesting materials at any given timepoint. Yet, because bumble bees store nectar within their brood cluster, our estimate of microcolony mass also includes nectar acquisition and depletion. Nevertheless, the metric of colony mass is still relevant as stored nectar is critical for brood incubation and worker caloric intake [@Heinrich2004; @Goulson2008; @Rotheray2017].  Regardless of its various components, colony mass is best used in tandem with demographic or additional physical characteristics of the colony (e.g. estimated colony volume) in inferring colony “success”. Patterns of mass gain/loss are likely more appropriate to describe relative food intake and consumption, rather than reproductive output.  Despite this, colony mass is still an important metric given that, for many species, colony size is an important precursor to the reproductive switch point of the colony [@Goulson2008].

## Drone production
A lack of an interaction between total food and temporal availability revealed a statistically clear, positive effect of increased food abundance on drone production independent of temporal availability.  This result supports our hypothesis regarding _B. impatiens_ tolerance of highly variable food environments.  That is, over time for _B.impatiens_, precisely when food is available is less important to drone productivity than how much food is available.  In fact, populations of _B. impatiens_ remain stable in agriculturally dominated landscapes despite dearth periods of food, while other species (namely _B. affinis_ and _B. terricola_) have declined [@Cameron2011]. Worker polymorphism within _B. impatiens_ could explain this tolerance: smaller workers are more robust to periods of nectar starvation [@Couvillon2010]. In our study, however, worker body size was not controlled for as workers selected for a given microcolony were selected at random from natal colonies.  Worker mortality was also consistent across microcolonies and treatments, suggesting we did not unintentionally select smaller, more tolerant workers for any given treatment.  Given that microcolony mass in pulsed-treatment microcolonies increased more during food pulses, it could also be that workers increased food storage in order to functionally "smooth" their resource landscape over time.  Such caching behavior, common among other insects and birds [@VanderWall1990], would allow for the consistent production of drones despite dearth periods encompassing the pulses.

Drone size was, on average, greater in high ration treated microcolonies, regardless of temporal availability.  This is an important difference as drones are crucial for gene flow via dispersal.  Therefore, colonies producing relatively large-bodied drones [which correlates with increased flight range in worker bumble bees @Greenleaf2007b; and with increased sperm number in honey bees @Schluns2003] may be more successful in contributing genetic information to subsequent generations.  We might also expect that the total food-driven difference in drone size that we observed in this study would translate to full-colonies producing workers rather than drones.  Larger workers are known to have colony-level benefits thanks to increased foraging range and efficiency [@Peat2005; @Rotheray2017].  Interestingly, the treatment that produced the numerically largest drones, high-pulsed rations, was one of the least efficient at converting pollen into drones (though the difference in pollen consumption efficiency was not statistically clear).  This suggests that while _B. impatiens_ seems robust to temporal fluctuations in food abundance it comes at a cost of efficiency of food use.

Environmental stressors like variability in the abundance of and temporal availability of food are likely to impact species differently [@Roulston2011; @Woodard2017].  While studies examining _B. impatiens_ reproductive response to variable food abundance are lacking, experiments have documented enhanced reproductive success in variable resource environments for the European ecological analog _B. terrestris_ [@Schmid-Hempel1998a].  For example, @Schmid-Hempel1998a found that variable access to food led to an increased rate of food collection (mass gain) and increased production of workers.  We found similar patterns of increased food collection rate among _B. impatiens_ microcolonies fed variable rations, especially during the second food pulse in our experiment. However, we did not find variable food abundance elevated drone production relative to constant ration microcolonies.  Despite this, the ability for the microcolonies provided pulsed-rations to consistently produce drones suggests a mechanism for dealing with dearth periods of food availability.  Increasing food collection and storage during pulses could allow _B. impatiens_ colonies to thrive in agricultural landscapes with highly variable floral resources.  This can be contrasted to other bumble bee species that may not engage in such foraging behaviors, or that have a more limited diet breadth [@Wood2019], potentially explaining the loss of these species (e.g., _B. affinis_ and _B. terricola_) from landscapes dominated by agriculture.  Given this, it is important for future studies to consider comparative, interspecies studies which could identify species most sensitive to temporal bottlenecks in food availability.  Such work would build on findings highlighting the importance of resource continuity for wild bee communities [@Martins2018], and could aid in the design of agricultural landscapes that support ecosystem service providers such as bumble bees [@Landis2017].

## Conclusions
Disentangling the contribution of environmental stressors to bumble bee decline is imperative if we are to be successful in stemming further losses.  In this study, we showed that temporal and total pollen and nectar availability interact to impact bumble bee microcolony growth, with microcolonies provided more, temporally consistent food growing the most.  We also showed that reproductive output was driven by total, and not temporal pollen and nectar availability: microcolonies provided full rations of pollen and nectar produced the most drones.  While we examined laboratory microcolonies, the responses observed should be indicative of a standard, queen-right colony [@Tasei2008; @Dance2017].  If anything, free-foraging, queen-right colonies are likely to see exacerbated responses to similar treatments, given that foraging is the most energetically expensive and risky activity for bumble bees.  Even though temporal availability did not impact the reproductive output of _B. impatiens_ in this study, other species of bumble bee need to be examined for their ability to cope with boom-bust cycles of food availability.  The implications of this work to managing landscapes is clear: at the least, an increase in total floral abundance (i.e., pollen and nectar) would likely have benefits to bumble bee colony reproduction.  However, increasing both total floral abundance as well as temporal continuity would benefit species tolerant of dearth periods, as well as those sensitive to nutritional stress.  Such efforts are essential to limit further loss of essential ecosystem service providers like bumble bees.

# Acknowledgements
We would like to thank Neal Williams for feedback that greatly improved this manuscript.  This project was funded by UW Madison Hatch award No. XXXXX.  We thank Biobest and Koppert Biological Systems for providing queen-right colonies for this experiment.  Data and code for all analyses, figures, and the manuscript will be made publically available upon publication at https://github.com/jhemberger.

# Author contributions
JH and CG conceived of and designed the experiment.  JH, AF, and GW conducted the experiment.  JH performed the statistical analyses and wrote the manuscript with input from CG throughout.  

\newpage
![Conceptual depiction of variation in total resource amount as well as temporal availability.  Total resource abundance increases along the x-axis, while temporal variance increases on the y-axis.  We designed treatments based on the intersecting regions of total food abundance and temporal availability, with diagrams of food presentation shown in the inset graphs. The area under the curve in yellow represents the amount of food presented to bumble bee microcolonies, with both pollen and nectar following the same pattern.  The area under the curve is equivalent within each food quantity category.](./fig1_conceptual.png)

\clearpage

\newpage
![(a) Least square mean (LSM) estimated mass throughout the experiment and (b) Least square mean terminal brood mass.  Letters indicate significant differences both within and across temporal treatment categories (constant and variable).  Error bars are 95% confidence intervals.  Difference of 1 interval feeding day is equal to 3 Julian days.](./fig2_mc_mass.png)

\clearpage

\newpage
![(a,c) Least square mean (LSM) estimated growth rate by time periods relative to pulses.  Letters indicate significant differences both within and across temporal treatment categories (constant and variable) _within periods_ (x-axis), and asterisks represent growth estimates significantly different than 0.  Error bars are 95% confidence intervals. (b,d) Least square mean growth rates by treatment.  Letters indicate significant differences both within and across temporal treatments.  Error bars are 95% confidence intervals Difference of 1 interval feeding day is equal to 3 Julian days.](./fig3_mc_growth.png)

\clearpage

\newpage
![(a,c) Least square mean (LSM) estimated cumulative drone production and (b,d) Least square mean total drone production.  Letters indicate significant differences both within and across temporal treatment categories (constant and variable).  Error bars are 95% confidence intervals.  Difference of 1 interval feeding day is equal to 3 Julian days.](./fig4_drones.png)

\clearpage

\newpage
# References